
all: dup0 fork0 fork1 fork2 exec0 shell0 shell1

dup0: dup0.c
	gcc -o dup0 dup0.c

fork0: fork0.c
	gcc -o fork0 fork0.c

fork1: fork1.c
	gcc -o fork1 fork1.c

fork2: fork2.c
	gcc -o fork2 fork2.c
	
exec0: exec0.c
	gcc -o exec0 exec0.c

shell0: shell0.c
	gcc -o shell0 shell0.c

shell1: shell1.c
	gcc -o shell1 shell1.c
	
clean:
	rm dup0 fork0 fork1 fork2 exec0 shell0 shell1

